version: "3"

services:

  mail:
    image: djfarrelly/maildev
    restart: unless-stopped
    ports:
      - 1025:25
      - 1080:80
  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password # username: postgres
      POSTGRES_DB: db
    ports:
      - 5432:5432

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  app:
    build: .
    command: /start-reload.sh
    depends_on:
     - db
     - mail
    ports:
      - 80:80
    volumes:
     - ${PWD}/:/app
    #  - ${HOME}/.aws:/root/.aws
    # environment:
    # - AWS_ACCESS_KEY_ID
    # - AWS_SECRET_ACCESS_KEY
    